### ISSUE TITLE
[Help]: What is a structure of "token" file from "tokenPath"

### ISSUE THREAD

**Issue by JaLe29** [ismail-codinglab/gmail-inbox#4]
Hi,

can you privde example of token file from tokenPath (your constructor `constructor(credentialsJsonPath: string, tokenPath?: string);`).

I found, that in token file should be (from google code):
```
        if (!thisCreds.access_token && !thisCreds.refresh_token && !this.apiKey) {
            throw new Error('No access, refresh token or API key is set.');
        }
```

What is access_token, refresh_token  and apiKey?

I am trying to load my token from config file instead of manual authorization on my kubernetes cluster. Thank you.

**Comment by ismail-codinglab** [comment]
The token path is the path to the Oauth2 Auth file, this is based on the credentials file

This is how the credentials file should look like: https://camo.githubusercontent.com/0495d8fe1550b2710d785b853f6dcb228301ddf08683de067eaf8186dc3c45ff/68747470733a2f2f692e6962622e636f2f317374676e32382f63726564656e7469616c732e706e67

When you run the application it will use this credentials file to create an Auth file with access token and refresh token properties like: 

https://github.com/ismail-codinglab/gmail-inbox/blob/master/gmail-token.json

To obtain this json file please follow all steps and run the code
