### ISSUE TITLE
[BUG]: Precision param in findMessages doesn`t work

### ISSUE THREAD

**Issue by JaLe29** [ismail-codinglab/gmail-inbox#5]
I would like to filter emails in interval>

```
{
  before: { date: 2020-08-24T04:00:00.000Z, precision: 'milliseconds' },
  after: { date: 2020-08-23T22:00:00.000Z, precision: 'milliseconds' }
}
```

It returns an empty array, but i am pretty sure that email in this interval exist, what is wrong?

**Comment by ismail-codinglab** [comment]
I'd say try `olderThan` and `newerThan`

**Comment by JaLe29** [comment]
Same, its not working in gmail also, looks like gmail not support filter by timestamp

**Comment by JaLe29** [comment]
I found that problem is that libary is sending timestamp like:
```
1610125200000
```
**but it MUST be**
```
1610125200
```

**Comment by ismail-codinglab** [comment]
Oh that works?

If so i'd appreciate a PR

I've made this in my leisure time

**Comment by JaLe29** [comment]
Fixed in https://github.com/ismail-codinglab/gmail-inbox/pull/6

**Comment by ismail-codinglab** [comment]
Great work 👍👍

**Comment by ismail-codinglab** [comment]
New version is out 1.4.0 including this fix
