### ISSUE TITLE
[Help] How to use 2 different Gmail account in one project?

### ISSUE THREAD

**Issue by Marcin3** [ismail-codinglab/gmail-inbox#7]
In my project, I use different users for different environments. There is any way to use 2 different gmail-token? 
I am thinking about copy proper file according to the environment but I am not sure if it is the best solution

Extra question
What is the default value of these parameters?  
- timeTillNextCallInSeconds
- maxWaitTimeInSeconds?

**Comment by ismail-codinglab** [comment]
## Question 1
Yes!

https://github.com/ismail-codinglab/gmail-inbox/blob/master/src/Inbox.ts

Inbox class accepts 2 parameters 
https://github.com/ismail-codinglab/gmail-inbox/blob/aa71619c554ca9200007c3a279a178e33696d381/src/Inbox.ts#L36

You can do
```
let inbox1 = new Inbox('inbox1-secret.json','inbox1-token.json');
let inbox2 = new Inbox('inbox2-secret.json','inbox2-token.json');
```

## Question 2
https://github.com/ismail-codinglab/gmail-inbox/blob/aa71619c554ca9200007c3a279a178e33696d381/src/Inbox.ts#L151-L152
they are `5` and `60` respectively

**Comment by ismail-codinglab** [comment]
If this answers your question let me know n you can close it

**Comment by Marcin3** [comment]
Thank you for your answer.
