### ISSUE TITLE
Bug with before as SearchQuery

### ISSUE THREAD

**Issue by Marcin3** [ismail-codinglab/gmail-inbox#8]
I have SearchQuery like that: 

        const thirtyMinutesBefore = new Date();
        thirtyMinutesBefore.setMinutes(thirtyMinutesBefore.getMinutes() - 30);
        
        return await inbox.waitTillMessage({
            mustContainText: text,
            before: {
                date: thirtyMinutesBefore,
                precision: 'milliseconds',
            },
        } as SearchQuery);`

On the console is log like that 

```
Gmail-inbox: finding message based on SearchQuery: {
  mustContainText: 'text',
  before: { date: 2021-03-22T10:10:38.786Z, precision: 'milliseconds' }
}
```
And I get a message from 10:40 so it is probably  a bug 

` "receivedOn": "Mon, 22 Mar 2021 10:40:38 +0000"`

**Comment by Marcin3** [comment]
It could be connected with this PR https://github.com/ismail-codinglab/gmail-inbox/pull/6 and the problem that this is not on the npm version 1.3.1

![image](https://user-images.githubusercontent.com/10815386/111980305-65dd5200-8b06-11eb-8465-fc16961d2ff2.png)

**Comment by Marcin3** [comment]
Fix is here https://github.com/ismail-codinglab/gmail-inbox/pull/9

**Comment by ismail-codinglab** [comment]
Cool!

**Comment by ismail-codinglab** [comment]
Thanks senior dev :)

**Comment by ismail-codinglab** [comment]
New version is out 1.4.0 including this fix
